version: '3'
services:
  twitch-radio-api:
    image: guns-for-hire/api
    environment:
      PORT: ${PORT}
      URL: ${URL}
      DB_CONNECT: ${DB_CONNECT}
networks:
  default:
    external: true
    name: tycho_default
